### ISSUE TITLE
名前にNIMがついてないと公開できないようにする

### ISSUE THREAD

**Issue by Shanpan2** [oshurecat/NeutralInModes#20]
## タイトル通り
MOD名がないとどういうMODかわからなくなる。そのためSNRやTOHと同様にすべきであると考えてます。(ほかの人次第でありますが)
## 追記
ホストモードの場合すべての機種でプレイはできるが、通常モードやタスクバトルモードの場合PCオンリーでしかプレイできないためホストモード以外に設定した場合PC以外をキックする機能を追加してほしいと考えてる。

**Comment by Shanpan2** [comment]
それぞれ別のissue作った方がいいかな?

**Comment by oshurecat** [comment]
部屋が匿名化されてるので今はいいかと思います
